# Generated by Django 3.2.9 on 2023-04-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('JR', 'Junior'), ('SR', 'Senior')], default='JR', max_length=2)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
